/**
 * Build a custom Lucide icons bundle with only the icons we use.
 * This reduces bundle size from ~378KB to ~30KB.
 *
 * Run with: node scripts/build-lucide.js
 */

const fs = require('fs');
const path = require('path');

// All icons used in the codebase (from templates and JS)
const USED_ICONS = [
  'alert-triangle',
  'archive',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'book',
  'book-open',
  'calculator',
  'calendar',
  'camera',
  'check',
  'check-circle',
  'chevron-down',
  'chevron-right',
  'chevron-up',
  'download',
  'edit-2',
  'file-text',
  'git-merge',
  'github',
  'history',
  'home',
  'image',
  'info',
  'key',
  'layout-dashboard',
  'library',
  'log-out',
  'mail',
  'mail-check',
  'menu',
  'pencil',
  'plus',
  'plus-circle',
  'refresh-cw',
  'rotate-ccw',
  'scan-line',
  'search',
  'search-x',
  'send',
  'settings',
  'shield',
  'sparkles',
  'star',
  'sticky-note',
  'tags',
  'trash-2',
  'upload',
  'user',
  'wifi-off',
  'wrench',
  'x'
];

// Convert kebab-case to PascalCase for Lucide imports
function toPascalCase(str) {
  return str
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

// Generate the custom bundle source
function generateBundle() {
  const imports = USED_ICONS.map(icon => {
    const pascalName = toPascalCase(icon);
    return `  ${pascalName}`;
  }).join(',\n');

  const iconMap = USED_ICONS.map(icon => {
    const pascalName = toPascalCase(icon);
    return `  '${icon}': ${pascalName}`;
  }).join(',\n');

  return `// Custom Lucide bundle - only icons used in MyBookShelf
// Generated by scripts/build-lucide.js
import {
${imports},
  createIcons as lucideCreateIcons
} from 'lucide';

// Map icon names to their implementations
const icons = {
${iconMap}
};

// Custom createIcons that only uses our subset
function createIcons(options = {}) {
  lucideCreateIcons({
    ...options,
    icons
  });
}

// Export for global access
window.lucide = { createIcons, icons };
`;
}

// Ensure output directory exists
const outputDir = path.join(__dirname, '..', 'src', 'js', 'vendor');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Write the source file
const sourcePath = path.join(outputDir, 'lucide-custom.js');
fs.writeFileSync(sourcePath, generateBundle());
console.log(`Generated: ${sourcePath}`);
console.log(`Icons included: ${USED_ICONS.length}`);
